import { Course, Ebook, VideoLesson } from './types';

export const courses: Course[] = [
  {
    id: '1',
    title: 'Marketing Digital do Zero ao PRO',
    description: 'Aprenda estratégias completas de marketing digital, desde conceitos básicos até técnicas avançadas de conversão.',
    category: 'marketing',
    level: 'iniciante',
    duration: '12 horas',
    modules: 8,
    plan: 'free',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop',
    instructor: 'Ana Silva',
    rating: 4.8,
    students: 1250
  },
  {
    id: '2',
    title: 'Vendas Presenciais: Técnicas Avançadas',
    description: 'Domine a arte da venda presencial com técnicas comprovadas de persuasão e fechamento.',
    category: 'vendas',
    level: 'intermediario',
    duration: '8 horas',
    modules: 6,
    plan: 'pro',
    thumbnail: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=400&h=250&fit=crop',
    instructor: 'Carlos Mendes',
    rating: 4.9,
    students: 890
  },
  {
    id: '3',
    title: 'Funil de Vendas Completo',
    description: 'Construa funis de vendas eficientes que convertem visitantes em clientes fiéis.',
    category: 'ambos',
    level: 'iniciante',
    duration: '10 horas',
    modules: 7,
    plan: 'free',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop',
    instructor: 'Mariana Costa',
    rating: 4.7,
    students: 2100
  },
  {
    id: '4',
    title: 'Copywriting para Vendas',
    description: 'Escreva textos persuasivos que vendem. Aprenda as técnicas dos melhores copywriters do mundo.',
    category: 'marketing',
    level: 'intermediario',
    duration: '6 horas',
    modules: 5,
    plan: 'pro',
    thumbnail: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&h=250&fit=crop',
    instructor: 'Pedro Alves',
    rating: 4.9,
    students: 1560
  },
  {
    id: '5',
    title: 'Negociação e Fechamento',
    description: 'Técnicas profissionais de negociação para fechar mais vendas e aumentar seu ticket médio.',
    category: 'vendas',
    level: 'avancado',
    duration: '9 horas',
    modules: 6,
    plan: 'pro',
    thumbnail: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=400&h=250&fit=crop',
    instructor: 'Roberto Santos',
    rating: 4.8,
    students: 720
  },
  {
    id: '6',
    title: 'Redes Sociais para Negócios',
    description: 'Aprenda a usar Instagram, Facebook e TikTok para vender mais e construir sua marca.',
    category: 'marketing',
    level: 'iniciante',
    duration: '7 horas',
    modules: 5,
    plan: 'free',
    thumbnail: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=250&fit=crop',
    instructor: 'Julia Ferreira',
    rating: 4.6,
    students: 3200
  }
];

export const ebooks: Ebook[] = [
  {
    id: '1',
    title: 'Guia Completo de Marketing Digital',
    description: 'E-book definitivo com todas as estratégias de marketing digital que você precisa conhecer.',
    category: 'marketing',
    pages: 120,
    plan: 'free',
    cover: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=400&fit=crop',
    author: 'Ana Silva',
    downloads: 5400,
    rating: 4.7
  },
  {
    id: '2',
    title: '50 Técnicas de Vendas Presenciais',
    description: 'As melhores técnicas de vendas presenciais compiladas em um único material.',
    category: 'vendas',
    pages: 85,
    plan: 'pro',
    cover: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop',
    author: 'Carlos Mendes',
    downloads: 2100,
    rating: 4.9
  },
  {
    id: '3',
    title: 'Copywriting: Fórmulas que Vendem',
    description: 'Fórmulas comprovadas de copywriting para criar textos que convertem.',
    category: 'marketing',
    pages: 95,
    plan: 'pro',
    cover: 'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=300&h=400&fit=crop',
    author: 'Pedro Alves',
    downloads: 3200,
    rating: 4.8
  },
  {
    id: '4',
    title: 'Primeiros Passos nas Vendas',
    description: 'Guia essencial para quem está começando do zero no mundo das vendas.',
    category: 'vendas',
    pages: 65,
    plan: 'free',
    cover: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=300&h=400&fit=crop',
    author: 'Roberto Santos',
    downloads: 6800,
    rating: 4.6
  },
  {
    id: '5',
    title: 'Instagram para Vendas',
    description: 'Como usar o Instagram para vender mais e construir autoridade no seu nicho.',
    category: 'ambos',
    pages: 78,
    plan: 'free',
    cover: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=300&h=400&fit=crop',
    author: 'Julia Ferreira',
    downloads: 8900,
    rating: 4.7
  },
  {
    id: '6',
    title: 'Funil de Vendas: Guia Prático',
    description: 'Construa funis de vendas eficientes passo a passo com este guia prático.',
    category: 'ambos',
    pages: 110,
    plan: 'pro',
    cover: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=300&h=400&fit=crop',
    author: 'Mariana Costa',
    downloads: 4100,
    rating: 4.8
  }
];

export const videoLessons: VideoLesson[] = [
  {
    id: '1',
    title: 'Como Criar Anúncios que Convertem',
    description: 'Aprenda a criar anúncios irresistíveis no Facebook e Instagram que geram vendas reais.',
    category: 'marketing',
    duration: '15:30',
    plan: 'free',
    thumbnail: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=600&h=400&fit=crop',
    videoUrl: 'https://example.com/video1',
    aiGenerated: true,
    views: 8500,
    rating: 4.8,
    topics: ['Facebook Ads', 'Instagram Ads', 'Copywriting', 'Segmentação']
  },
  {
    id: '2',
    title: 'Técnicas de Abordagem em Vendas Presenciais',
    description: 'Domine as melhores técnicas de abordagem para conquistar clientes no presencial.',
    category: 'vendas',
    duration: '22:15',
    plan: 'pro',
    thumbnail: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&h=400&fit=crop',
    videoUrl: 'https://example.com/video2',
    aiGenerated: true,
    views: 5200,
    rating: 4.9,
    topics: ['Abordagem', 'Rapport', 'Linguagem Corporal', 'Persuasão']
  },
  {
    id: '3',
    title: 'SEO para Iniciantes: Ranqueie no Google',
    description: 'Estratégias práticas de SEO para aparecer na primeira página do Google.',
    category: 'marketing',
    duration: '18:45',
    plan: 'free',
    thumbnail: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?w=600&h=400&fit=crop',
    videoUrl: 'https://example.com/video3',
    aiGenerated: true,
    views: 12300,
    rating: 4.7,
    topics: ['SEO', 'Google', 'Palavras-chave', 'Conteúdo']
  },
  {
    id: '4',
    title: 'Gatilhos Mentais que Vendem',
    description: 'Os 10 gatilhos mentais mais poderosos para aumentar suas vendas imediatamente.',
    category: 'ambos',
    duration: '20:00',
    plan: 'pro',
    thumbnail: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600&h=400&fit=crop',
    videoUrl: 'https://example.com/video4',
    aiGenerated: true,
    views: 15600,
    rating: 4.9,
    topics: ['Gatilhos Mentais', 'Psicologia', 'Persuasão', 'Vendas']
  },
  {
    id: '5',
    title: 'Email Marketing que Converte',
    description: 'Crie campanhas de email marketing que geram resultados e fidelizam clientes.',
    category: 'marketing',
    duration: '16:20',
    plan: 'free',
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&h=400&fit=crop',
    videoUrl: 'https://example.com/video5',
    aiGenerated: true,
    views: 9800,
    rating: 4.6,
    topics: ['Email Marketing', 'Automação', 'Copywriting', 'Conversão']
  },
  {
    id: '6',
    title: 'Objeções: Como Contornar e Fechar',
    description: 'Aprenda a lidar com objeções e transformá-las em oportunidades de venda.',
    category: 'vendas',
    duration: '24:10',
    plan: 'pro',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop',
    videoUrl: 'https://example.com/video6',
    aiGenerated: true,
    views: 7400,
    rating: 4.8,
    topics: ['Objeções', 'Fechamento', 'Negociação', 'Técnicas']
  },
  {
    id: '7',
    title: 'Stories que Vendem no Instagram',
    description: 'Estratégias para criar stories que engajam e convertem seguidores em clientes.',
    category: 'marketing',
    duration: '14:30',
    plan: 'free',
    thumbnail: 'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=600&h=400&fit=crop',
    videoUrl: 'https://example.com/video7',
    aiGenerated: true,
    views: 18900,
    rating: 4.7,
    topics: ['Instagram', 'Stories', 'Engajamento', 'Vendas']
  },
  {
    id: '8',
    title: 'Prospecção Ativa: Encontre Clientes',
    description: 'Técnicas eficazes de prospecção para encontrar e conquistar novos clientes.',
    category: 'vendas',
    duration: '19:45',
    plan: 'pro',
    thumbnail: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600&h=400&fit=crop',
    videoUrl: 'https://example.com/video8',
    aiGenerated: true,
    views: 6100,
    rating: 4.9,
    topics: ['Prospecção', 'Cold Call', 'LinkedIn', 'Networking']
  }
];
